export const SET_VEHICLE_ID = 'SET_VEHICLE_ID';

export const LOAD_VEHICLE_INFO = 'LOAD_VEHICLE_INFO';
export const LOADING_VEHICLE_INFO = 'LOADING_VEHICLE_INFO';
export const LOADED_VEHICLE_INFO = 'LOADED_VEHICLE_INFO';

export const SELECT_DAY = 'SELECT_DAY';

export const SET_PAYMENT = 'SET_PAYMENT';
export const SUCCESSFUL_PAYMENT = 'SUCCESSFUL_PAYMENT';
export const FAILED_PAYMENT = 'FAILED_PAYMENT';
